-- SilkByteX work/project CMS table + seed data.
-- Run this in Supabase SQL Editor if the admin Work page has no editable records.
-- The table name and column names match the Prisma `Project` model.

create table if not exists "Project" (
  "id" text primary key,
  "title" text not null,
  "slug" text not null unique,
  "category" text,
  "kicker" text,
  "client" text,
  "year" text,
  "shortDescription" text,
  "longDescription" text,
  "servicesUsed" text,
  "challenge" text,
  "approach" text,
  "outcome" text,
  "quoteText" text,
  "quoteAttribution" text,
  "gallery" text,
  "color" text default '#000000',
  "projectStatus" text default 'published',
  "isFeatured" boolean not null default false,
  "isDraft" boolean not null default false,
  "sortOrder" integer not null default 0,
  "imageUrl" text,
  "metaTitle" text,
  "metaDescription" text,
  "createdAt" timestamp(3) without time zone not null default current_timestamp,
  "updatedAt" timestamp(3) without time zone not null default current_timestamp
);

insert into "Project" (
  "id", "title", "slug", "category", "kicker", "client", "year",
  "shortDescription", "longDescription", "servicesUsed", "challenge",
  "approach", "outcome", "quoteText", "quoteAttribution", "color",
  "projectStatus", "isFeatured", "isDraft", "sortOrder", "createdAt", "updatedAt"
) values
(
  'fallback-ai-automation-os',
  'AI Automation OS',
  'ai-automation-os',
  'Automation',
  'AI Systems / Operations',
  'Operations team',
  '2026',
  'A connected automation layer for replacing repetitive operations with reliable AI-assisted workflows.',
  'SilkByteX designed a lightweight operating system for teams that need approvals, intake, summaries, notifications, and dashboards to move without manual follow-up.',
  'AI Systems, Workflow Automation, Internal Tools',
  'The team had important work scattered across forms, inboxes, spreadsheets, and chat. Every handoff depended on someone remembering the next step.',
  'We mapped the operational flow, designed a central data model, and connected the repetitive steps through readable automations and human review checkpoints.',
  'The result is a clearer internal system where work is visible, repetitive tasks are automated, and team leads can see what needs attention.',
  'The system makes our daily operations feel calmer and easier to trust.',
  'Operations lead',
  '#8fd8c7',
  'published',
  true,
  false,
  1,
  current_timestamp,
  current_timestamp
),
(
  'fallback-commerce-engine',
  'Commerce Engine',
  'commerce-engine',
  'Commerce',
  'E-commerce Platform',
  'Digital commerce brand',
  '2026',
  'A modular commerce platform for fast product launches, campaign management, and cleaner storefront operations.',
  'SilkByteX built a commerce foundation that connects catalog data, launch workflows, landing pages, and operational dashboards into one manageable system.',
  'E-commerce Development, CMS Architecture, Growth Systems',
  'Launching products required too many manual updates across disconnected tools, which slowed campaigns and created avoidable mistakes.',
  'We shaped the platform around reusable product blocks, structured content, clean order visibility, and fast publishing workflows.',
  'The commerce team can launch faster, manage content with less developer support, and keep the storefront aligned with live operations.',
  'Product launches became faster because the platform finally matched how our team works.',
  'Commerce director',
  '#f2ce4a',
  'published',
  true,
  false,
  2,
  current_timestamp,
  current_timestamp
),
(
  'fallback-founder-saas-dashboard',
  'Founder SaaS Dashboard',
  'founder-saas-dashboard',
  'SaaS',
  'Product Dashboard',
  'Founder-led SaaS',
  '2026',
  'A focused product dashboard that turns revenue, onboarding, retention, and support signals into readable decisions.',
  'SilkByteX created a dashboard experience for founders who need to understand product health quickly without digging through disconnected analytics tools.',
  'SaaS Product Development, Dashboard UX, Analytics Design',
  'The founder had data, but not a usable operating view. Important signals were buried across analytics, CRM, billing, and support tools.',
  'We prioritized the few metrics that drive action, designed clear dashboard states, and created a responsive interface for repeated daily use.',
  'The dashboard gives leadership a faster way to spot growth opportunities, onboarding issues, and retention risks.',
  'It finally feels like one place to understand the product instead of another reporting chore.',
  'SaaS founder',
  '#9ba6ff',
  'published',
  true,
  false,
  3,
  current_timestamp,
  current_timestamp
),
(
  'fallback-booking-platform',
  'Booking Platform',
  'booking-platform',
  'Platform',
  'Booking / Scheduling',
  'Service marketplace',
  '2026',
  'A conversion-focused booking system for appointments, availability, payments, and operational control.',
  'SilkByteX shaped a booking experience that helps customers move from interest to confirmed appointment while giving operators a cleaner way to manage calendars, capacity, and changes.',
  'Platform Design, Scheduling Logic, Payments, Dashboard UX',
  'Customers were dropping out during booking because availability, pricing, and confirmation steps felt disconnected.',
  'We redesigned the booking flow around clear decisions, resilient calendar logic, and a back-office dashboard that keeps operations in sync.',
  'The platform makes booking faster for customers and easier for internal teams to manage during busy periods.',
  'The new booking flow feels direct, polished, and much easier for our team to operate.',
  'Marketplace operator',
  '#ef8a74',
  'published',
  true,
  false,
  4,
  current_timestamp,
  current_timestamp
),
(
  'fallback-internal-operations-portal',
  'Internal Operations Portal',
  'internal-operations-portal',
  'Internal Tools',
  'Operations / Dashboard',
  'Growing service team',
  '2026',
  'A private operations portal for intake, approvals, task visibility, team handoffs, and leadership reporting.',
  'SilkByteX created a portal that turns scattered internal work into a single operational surface with the right views for contributors, managers, and leadership.',
  'Internal Tools, Dashboard Design, Workflow Systems',
  'Internal work was moving through too many informal channels, making ownership hard to track and delays hard to diagnose.',
  'We built role-based views, structured intake, approval states, and simple reporting around the team’s real operating rhythm.',
  'The team gained clearer ownership, faster handoffs, and a more reliable picture of active work.',
  'It gave our team one shared place to understand what is moving and what is stuck.',
  'Team lead',
  '#c7e66b',
  'published',
  true,
  false,
  5,
  current_timestamp,
  current_timestamp
),
(
  'fallback-brand-system-digital-studio',
  'Brand System for Digital Studio',
  'brand-system-digital-studio',
  'Branding',
  'Identity / Web System',
  'Digital studio',
  '2026',
  'A flexible digital brand system with typography, interface rules, content rhythm, and reusable website components.',
  'SilkByteX developed a digital-first identity system designed to keep a growing studio consistent across its website, decks, campaigns, and product surfaces.',
  'Brand Identity, Design System, Website Design',
  'The studio had strong ideas but no shared system, which made every new page and campaign feel like a fresh design problem.',
  'We created a focused brand foundation, modular layouts, expressive typography rules, and a reusable component vocabulary.',
  'The team can now create new digital surfaces faster while keeping the brand recognizable and premium.',
  'The system gave us a brand language we can actually use every week.',
  'Studio founder',
  '#d8c3ff',
  'published',
  true,
  false,
  6,
  current_timestamp,
  current_timestamp
),
(
  'fallback-growth-system',
  'Digital Growth System',
  'growth-system',
  'Growth',
  'Website / Funnel System',
  'B2B startup',
  '2026',
  'A website and growth system built around landing pages, lead routing, analytics, and rapid content iteration.',
  'SilkByteX turned a static marketing site into a growth-ready system where campaigns, landing pages, and conversion signals can improve together.',
  'Website Development, Growth Systems, Analytics',
  'The existing site looked acceptable but could not support fast campaigns, clear attribution, or confident content changes.',
  'We rebuilt the website around reusable page patterns, campaign-specific entry points, analytics events, and a cleaner publishing workflow.',
  'The team can launch targeted pages faster and understand which messages are actually creating qualified conversations.',
  'It stopped being just a website and became part of how we grow.',
  'Growth lead',
  '#82b7ff',
  'published',
  true,
  false,
  7,
  current_timestamp,
  current_timestamp
),
(
  'fallback-ai-support-console',
  'AI Support Console',
  'ai-support-console',
  'AI',
  'Support / Automation',
  'Customer success team',
  '2026',
  'An AI-assisted support console for triage, summaries, response drafting, and customer health visibility.',
  'SilkByteX designed a support workspace that helps teams move faster without losing judgment, context, or the human tone customers expect.',
  'AI Automation, SaaS Tools, Support Operations',
  'Support agents were switching between tickets, docs, CRM notes, and product data before they could answer simple requests.',
  'We designed a console that brings customer context together, drafts suggested replies, and highlights urgent signals for human review.',
  'The support team can respond with more context, reduce repetitive writing, and identify account risk sooner.',
  'It helps us answer faster without sounding automated.',
  'Customer success manager',
  '#f4a7c5',
  'published',
  true,
  false,
  8,
  current_timestamp,
  current_timestamp
)
on conflict ("slug") do update set
  "title" = excluded."title",
  "category" = excluded."category",
  "kicker" = excluded."kicker",
  "client" = excluded."client",
  "year" = excluded."year",
  "shortDescription" = excluded."shortDescription",
  "longDescription" = excluded."longDescription",
  "servicesUsed" = excluded."servicesUsed",
  "challenge" = excluded."challenge",
  "approach" = excluded."approach",
  "outcome" = excluded."outcome",
  "quoteText" = excluded."quoteText",
  "quoteAttribution" = excluded."quoteAttribution",
  "color" = excluded."color",
  "projectStatus" = excluded."projectStatus",
  "isFeatured" = excluded."isFeatured",
  "isDraft" = excluded."isDraft",
  "sortOrder" = excluded."sortOrder",
  "updatedAt" = current_timestamp;
